### PR TITLE
relax taggedalgebraic dependency

### PR DESCRIPTION
**Pull request by John-Colvin**
it's a real pain otherwise due to dependency clashes.

### CODE REVIEW

**Comment by joseph-wakeling-frequenz** [comment]
Hah, is it that simple?  I thought there had been some breaking changes which needed more intrusive version-specific changes.

**Comment by John-Colvin** [comment]
Well, I don't really know, but the tests pass ¯\_(ツ)_/¯

Hoping that someone who does know a bit better chooses whether to merge this or not.

**Comment by s-ludwig** [comment]
Should be fine, the breaking changes should be limited to rarely encountered corner cases. BTW, it may even make sense to require 0.11.x at some point and make use of `TaggedUnion` and `This`, which would make the code a bit prettier.

**Comment by John-Colvin** [comment]
Of course, to really get the benefit of this change, a new release here would be necessary.

**Comment by John-Colvin** [comment]
ping, still need a new release to get people to be able to use this

**Comment by joseph-wakeling-frequenz** [comment]
@John-Colvin 
> Well, I don't really know, but the tests pass ¯\(ツ)/¯

Apologies for the late feedback -- I think the issues I was seeing may have been about compiler version rather than `taggedalgebraic` version.  I'll submit a CI PR shortly that may illustrate the issue.

**Comment by joseph-wakeling-frequenz** [comment]
Oh wait, it's worse than that.  CI is still testing with `taggedalgebraic` v0.10.9, because of the fixed `dub.selections.json`.  So it's never actually validating that v0.11.x works.

Going by my own local testing we have a double bind here:

* `taggedalgebraic` v0.11.x works with the compilers used in current CI

* it will fail with DMD >= 2.086

That's what I saw in my own local testing when I first filed #44, which is why I didn't follow up quickly at the time.

**Comment by joseph-wakeling-frequenz** [comment]
In short, please do NOT create a new release until these issues are resolved (I've written up details in #44).  Otherwise there will be a lot of unhappy users of `std_data_json` ;-)

**Pull request merged**
